[table_info]
target_table = dws_sale_detail_daycount
comment = 用户购买商品按日明细宽表（轻度汇总）

[columns]
# 目标DWS字段 = 数据类型 | 字段注释 | 来源或计算逻辑
user_id = BIGINT | 用户ID | dwd_fact_order_info.user_id
order_date = STRING | 日期 | To_DATE(dwd_fact_order_info.create_time)
sku_id = BIGINT | 商品ID | dwd_fact_order_detail.sku_id
user_gender = STRING | 用户性别 | dim_user_info.gender
user_age = STRING | 用户年龄 | ROUND(ROUND(MONTHS_BETWEEN(do_date, birthday),0) / 12, 2)
user_level = STRING | 用户等级 | dim_user_info.user_level
sku_price = DECIMAL(16,2) | SKU单价 | dim_sku_info.price
sku_name = STRING | SKU名称 | dim_sku_info.sku_name
sku_tm_id = BIGINT | 品牌ID | dim_sku_info.tm_id
sku_category3_id = BIGINT | 三级分类ID | dim_sku_info.category3_id
sku_category2_id = BIGINT | 二级分类ID | dim_sku_info.category2_id
sku_category1_id = BIGINT | 一级分类ID | dim_sku_info.category1_id
sku_category3_name = STRING | 三级分类名称 | dim_sku_info.category3_name
sku_category2_name = STRING | 二级分类名称 | dim_sku_info.category2_name
sku_category1_name = STRING | 一级分类名称 | dim_sku_info.category1_name
spu_id = BIGINT | SPU ID | dim_sku_info.spu_id
sku_num = BIGINT | 当日购买个数 | SUM(dwd_fact_order_detail.sku_num)
order_count = BIGINT | 当日下单单数 | COUNT(DISTINCT dwd_fact_order_detail.order_id)
order_amount = DECIMAL(16,2) | 当日下单金额 | SUM(dwd_fact_order_detail.order_price * sku_num)
etl_time = TIMESTAMP | ETL处理时间 | current_timestamp()