[table_info]
target_table = dws_user_action
comment = 用户行为按日汇总宽表（记录单日下单与支付统计）

[columns]
# 目标DWS字段 = 数据类型 | 字段注释 | 来源或计算逻辑
user_id = BIGINT | 用户ID(主键) | dim_user_info
order_date = STRING | 日期 | dim_date.date_full
order_count = BIGINT | 当日下单数 | COUNT(dwd_fact_order_info.id)
order_amount = DECIMAL(16,2) | 当日下单金额 | SUM(dwd_fact_order_info.total_amount)
payment_count = BIGINT | 当日支付单数 | COUNT(dwd_fact_payment_info.id)
payment_amount = DECIMAL(16,2) | 当日支付金额 | SUM(dwd_fact_payment_info.total_amount)
etl_time = TIMESTAMP | ETL处理时间 | current_timestamp()