[table_info]
target_table = ads_sale_tm_category1_stat_mn
comment = 品牌与一级品类月度复购率分析表

[columns]
# 目标字段 = 数据类型 | 字段注释 | 转换逻辑
tm_id = BIGINT | 品牌ID(主键) | dws_sale_detail_daycount.sku_tm_id
category1_id = BIGINT | 一级品类ID(主键) | dws_sale_detail_daycount.sku_category1_id
category1_name = STRING | 一级品类名称 | dws_sale_detail_daycount.sku_category1_name
buycount = BIGINT | 月内购买人数 | COUNT(DISTINCT user_id)
buy_twice_last = BIGINT | 购买2次及以上人数 | COUNT(DISTINCT user_id) WHERE count >= 2
buy_twice_last_ratio = DECIMAL(16,4) | 单次复购率 | buy_twice_last / buycount
buy_3times_last = BIGINT | 购买3次及以上人数 | COUNT(DISTINCT user_id) WHERE count >= 3
buy_3times_last_ratio = DECIMAL(16,4) | 多次复购率 | buy_3times_last / buycount
stat_mn = STRING | 统计月份 | substr(do_date, 1, 7)
stat_date = STRING | 汇总日期(主键) | do_date
etl_time = TIMESTAMP | ETL处理时间 | current_timestamp()