[table_info]
target_table = dim_user_info
comment = 用户维度表（安全脱敏，剔除密码敏感字段）


[columns]
# 目标DWD字段 = 数据类型 | 字段注释 | 来源ODS映射或转换逻辑
id = BIGINT | 用户编号(主键) | ods_user_info.id
login_name = STRING | 用户登录名 | ods_user_info.login_name
nick_name = STRING | 用户昵称 | ods_user_info.nick_name
name = STRING | 用户真实姓名 | ods_user_info.name
phone_num = STRING | 手机号(脱敏处理) | CONCAT(SUBSTR(ods_user_info.phone_num,1,3),'****',SUBSTR(ods_user_info.phone_num,8,4))
email = STRING | 邮箱地址 | ods_user_info.email
user_level = STRING | 用户级别 | ods_user_info.user_level
birthday = STRING | 用户生日 | ods_user_info.birthday
gender = STRING | 用户性别(M/F) | (CASE WHEN ods_user_info.gender='M' THEN '男' ELSE '女' END)
create_time = TIMESTAMP | 注册时间 | ods_user_info.create_time
etl_time = TIMESTAMP | ETL处理时间 | current_timestamp()