ODS_DB_NAME=mall2
ODS_TABLE_NAME=ods_base_category2


# 表类型与分区策略配置
# IS_PARTITIONED: 是否开启分区 (true/false)
# PARTITION_COL: 分区字段名 (默认 dt)
# IS_DIM_TABLE: 是否为维度表 (true/false)
# IS_TRANSACTION_TABLE: 是否为事务表 (true/false)
IS_PARTITIONED=true
PARTITION_COL=dt
IS_DIM_TABLE=false
IS_TRANSACTION_TABLE=true