--查询EMP表所有员工的数据，同时显示一些统计值

SELECT EMPNO,
       SAL,
       SUM(SAL) OVER() AS SAL_SUM,
       ROUND(AVG(SAL) OVER(),2) AS SAL_AVG,
       MAX(SAL) OVER() AS SAL_MAX,
       MIN(SAL) OVER() AS SAL_MIN
FROM EMP;

--练习1：查询员工工号、姓名、工资、
--工资占比全公司工资支出的百分比保留两个小数点。
SELECT EMPNO,
       ENAME,
       SAL,
       ROUND(SAL/SUM(SAL) OVER() *100,2) || '%' AS SAL_PERCENT
FROM EMP;


--练习2：查询员工工号、姓名、工资、
--原奖金基础上加上全公司平均工资的10%。

SELECT EMPNO,
       ENAME,
       SAL,
       (SAL + 0.1 * AVG(SAL) OVER() ) AS SAL_PLUS_10_AVG
FROM EMP;

--练习3：查询各个岗位的工资合计，
--以及岗位工资合计在全公司工资支出中的百分比，保留两个小数点。
SELECT JOB,
       SUM(SAL),
       ROUND(SUM(SAL)/ (SUM(SUM(SAL)) OVER()) *100,2) || '%' AS JOB_SAL_PERCENT --这里的SUM套SUM感觉需要一点理解
FROM EMP
GROUP BY JOB;


--11点42分
--练习1：查询所有员工的姓名、岗位、工资、工资在岗位合计工资中的占比，保留两个小数点。
SELECT ENAME,
       JOB,
       SAL,
       ROUND((SAL / SUM(SAL) OVER(PARTITION BY JOB)) * 100, 2) || '%' AS SAL_RATIO_IN_JOB
FROM EMP;

--练习2：查询工资高于所处岗位平均工资的员工信息(用开窗函数来实现)。
SELECT *
FROM (
SELECT EMP.*,
       AVG(SAL) OVER(PARTITION BY JOB) AS AVG_SAL_IN_JOB
FROM EMP)
WHERE SAL > AVG_SAL_IN_JOB;


--练习3：查询人数不少于3人的岗位的员工信息(用开窗函数来实现)
SELECT *
FROM (
SELECT EMP.*,
       COUNT(EMP.EMPNO) OVER(PARTITION BY JOB) AS EMP_IN_JOB
FROM EMP) T2 -- 此处别名是为了适配其他SQL，ORCLE可以直接识别字段
WHERE T2.EMP_IN_JOB > 3;


--ORDER BY通常用于累加合计


--练习1：以下为年度四个月的收入表，查询每年度从1月份到4月份的收入累计
CREATE TABLE AMT622(YYYY NUMBER
					          ,MM NUMBER
                    ,AMT  NUMBER);
INSERT INTO AMT622 VALUES(2021,01,1000);
INSERT INTO AMT622 VALUES(2021,02,1500);
INSERT INTO AMT622 VALUES(2021,03,800);
INSERT INTO AMT622 VALUES(2021,04,200);
INSERT INTO AMT622 VALUES(2022,01,200);
INSERT INTO AMT622 VALUES(2022,02,1800);
INSERT INTO AMT622 VALUES(2022,03,1100);
INSERT INTO AMT622 VALUES(2022,04,630);
INSERT INTO AMT622 VALUES(2020,04,650);
INSERT INTO AMT622 VALUES(2020,03,670);
COMMIT;

SELECT * FROM AMT622;

SELECT YYYY,
       MM,
       AMT,
       SUM(AMT) OVER(PARTITION BY YYYY ORDER BY MM)
FROM AMT622
ORDER BY YYYY, MM;

--练习2：以下为年度四个月的收入表，查询每年度从1月份到4月份的收入累计
DROP TABLE AMT623;
CREATE TABLE AMT623(YYYYMM NUMBER
                    ,AMT  NUMBER);
INSERT INTO AMT623 VALUES(202101,1000);
INSERT INTO AMT623 VALUES(202102,1500);
INSERT INTO AMT623 VALUES(202103,800);
INSERT INTO AMT623 VALUES(202104,200);
INSERT INTO AMT623 VALUES(202201,200);
INSERT INTO AMT623 VALUES(202202,1800);
INSERT INTO AMT623 VALUES(202203,1100);
INSERT INTO AMT623 VALUES(202204,630);
COMMIT;

SELECT * FROM AMT623;

SELECT YYYYMM,
       AMT,
       SUM(AMT) OVER(PARTITION BY TO_CHAR(TO_DATE(YYYYMM,'YYYYMM'),'YYYY') ORDER BY TO_CHAR(TO_DATE(YYYYMM,'YYYYMM'),'MM')) AS SUM_OF_ORDER
FROM AMT623
ORDER BY YYYYMM;

--练习3：求出EMP表中每年入职的人数，
--以及按照年份升序排序求每年累计入职的人数
1980     2          2
1981     10         12
1982     1          13
....

SELECT COUNT(EMP.EMPNO),
       TO_CHAR(EMP.HIREDATE, 'YYYY'),
       SUM(COUNT(EMP.EMPNO)) OVER(ORDER BY TO_CHAR(EMP.HIREDATE, 'YYYY')) AS SUM_OF_ORDER,
       SUM(COUNT(EMP.EMPNO)) OVER(PARTITION BY NULL ORDER BY TO_CHAR(EMP.HIREDATE, 'YYYY')) AS SUM_OF_ORDER
FROM EMP
GROUP BY TO_CHAR(EMP.HIREDATE, 'YYYY')
ORDER BY TO_CHAR(EMP.HIREDATE, 'YYYY')
--不用PARTITION BY TO_CHAR(EMP.HIREDATE, 'YYYY') ，因为没有内部的分组了

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD';
SELECT EMP.*,TO_CHAR(HIREDATE, 'YYYY') FROM EMP


--15点17分
SELECT e.EMPNO,
       e.SAL,
       e.JOB,
       RANK() OVER(PARTITION BY e.JOB ORDER BY e.SAL DESC) RANK_NUM
FROM EMP e

SELECT e1.*,RANK_T.RANK_NUM
FROM
EMP e1
INNER JOIN (
SELECT e.EMPNO,
       e.DEPTNO,
       e.HIREDATE,
       RANK() OVER(PARTITION BY e.DEPTNO ORDER BY e.HIREDATE) AS RANK_NUM
FROM EMP e) RANK_T ON e1.EMPNO=RANK_T.EMPNO AND RANK_T.RANK_NUM in (1,2)

--优化
SELECT RANK_T.*
FROM
(SELECT e.*,
       RANK() OVER(PARTITION BY e.DEPTNO ORDER BY e.HIREDATE) AS RANK_NUM
FROM EMP e) RANK_T
WHERE RANK_T.RANK_NUM in (1,2)



--15点46分
--练习1：请在EMP表中查找每个员工他的前一个入职的员工信息
--展示字段：当前员工工号和入职日期、上一个入职的员工工号和入职日期、
--他们的入职间隔天数

SELECT e.EMPNO,
       e.HIREDATE,
       LAG(e.EMPNO,1,NULL)OVER(ORDER BY e.HIREDATE),
       LAG(e.HIREDATE,1,NULL)OVER(ORDER BY e.HIREDATE), 
       e.HIREDATE - LAG(e.HIREDATE,1,NULL)OVER(ORDER BY e.HIREDATE)
FROM EMP e


--练习2：请根据年度月份收入表 AMT623，查找每个月的环比、同比
--展示字段：日期、今年月收入、上个月收入、环比、去年月收入、同比
--如果收入为空则展示为0
--环比公式：（当月的收入-上个月的收入）/上个月的收入
--同比公式：（当年月的收入-去年月的收入）/去年月的收入

SELECT T2.YYYYMM,
       T2.AMT,
       NVL(T2.LAST_MONTH_AMT, 0),
       ROUND((T2.AMT - NVL(T2.LAST_MONTH_AMT, 0)) / NVL(T2.LAST_MONTH_AMT, T2.AMT) * 100, 2) || '%' AS MoM,
       NVL(T2.LAST_YEAR_MONTH_AMT, 0),
       ROUND((T2.AMT - NVL(T2.LAST_YEAR_MONTH_AMT, 0)) / NVL(T2.LAST_YEAR_MONTH_AMT, T2.AMT) * 100, 2) || '%' MoM_Over_YEAR
FROM(
SELECT T.*,
       LAG(T.AMT,1,NULL)OVER(ORDER BY YYYYMM) AS LAST_MONTH_AMT,
       LAG(T.AMT,1,NULL)OVER(PARTITION BY SUBSTR(YYYYMM,5) ORDER BY SUBSTR(YYYYMM,1,4)) AS LAST_YEAR_MONTH_AMT
FROM AMT623 T) T2







-- 创建薪资等级表
CREATE TABLE SALGRADE (
    GRADE NUMBER,  -- 薪资等级
    LOSAL NUMBER,  -- 最低薪水
    HISAL NUMBER   -- 最高薪水
);

-- 插入经典的 5 个等级数据
INSERT INTO SALGRADE VALUES (1, 700, 1200);
INSERT INTO SALGRADE VALUES (2, 1201, 1400);
INSERT INTO SALGRADE VALUES (3, 1401, 2000);
INSERT INTO SALGRADE VALUES (4, 2001, 3000);
INSERT INTO SALGRADE VALUES (5, 3001, 9999);
COMMIT;


--RANGE BEETWEEN
SELECT T.ENAME,
       T.HIREDATE,
       T.SAL,
       AVG(T.SAL)OVER(ORDER BY T.SAL RANGE BETWEEN 100 PRECEDING AND CURRENT ROW) SUMSAL
FROM EMP T;



--1321

--错误的思路，意图通过LEAD先找到第七天，然后下面的窗口不能套窗口，而如果不套窗口就会从原第一行开始算，会感觉不符合要求
SELECT --C.visited_on,--
        TO_CHAR(LEAD(visited_on, 6) OVER(ORDER BY visited_on), 'YYYY-MM-DD') AS visited_on,
        SUM(SUM(amount)) 
        OVER(ORDER BY (LEAD(visited_on, 6) OVER(ORDER BY visited_on)) RANGE BETWEEN 7 PRECEDING AND CURRENT ROW) AS amount,
        AVG(AVG(amount)) OVER(ORDER BY (LEAD(visited_on, 6) OVER(ORDER BY visited_on)) RANGE BETWEEN 7 PRECEDING AND CURRENT ROW) AS average_amount
FROM Customer C
GROUP BY visited_on
ORDER BY visited_on 


--正确思路，直接开算，后续把前六条干掉

SELECT C.visited_on,--
        --TO_CHAR(LEAD(visited_on, 6) OVER(ORDER BY visited_on), 'YYYY-MM-DD') AS visited_on,
        SUM(SUM(amount)) OVER(ORDER BY visited_on RANGE BETWEEN 6 PRECEDING AND CURRENT ROW) AS amount,
        ROUND(AVG(AVG(amount)) OVER(ORDER BY visited_on RANGE BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS average_amount,

FROM Customer C
WHERE visited_on >= (SELECT MIN(visit_new) FROM (SELECT LEAD(visited_on, 6) OVER(ORDER BY visited_on) AS visit_new FROM Customer))
GROUP BY visited_on
ORDER BY visited_on 

--答案
SELECT TO_CHAR(visited_on, 'YYYY-MM-DD') AS visited_on, amount, average_amount
FROM (SELECT C.visited_on,--
        SUM(SUM(amount)) OVER(ORDER BY visited_on RANGE BETWEEN 6 PRECEDING AND CURRENT ROW) AS amount,
        ROUND(AVG(SUM(amount)) OVER(ORDER BY visited_on RANGE BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS average_amount

FROM Customer C
GROUP BY visited_on
ORDER BY visited_on) T2 
WHERE visited_on >= (SELECT MIN(visit_new) FROM (SELECT LEAD(visited_on, 6) OVER(ORDER BY visited_on) AS visit_new FROM Customer GROUP BY visited_on))
