--练习1：查询EMP表中，各个部门的平均工资，保留一个小数点
SELECT emp.deptno, TRUNC(AVG(emp.sal), 1)
FROM EMP
GROUP BY emp.deptno


--练习2：执行以下建表语句，按照每10岁作为一个年龄段，统计各个年龄段的平均余额，平均余额保留两个小数点。
--建表语句---
--DROP TABLE USER622;
CREATE TABLE USER622(ID NUMBER --用户ID
                     ,AGE NUMBER  --用户年龄
                     ,DEPOSIT NUMBER(10,2) --用户余额
                     );
                     
INSERT INTO USER622 VALUES(1,21,5000);
INSERT INTO USER622 VALUES(2,29,450);
INSERT INTO USER622 VALUES(3,25,500);
INSERT INTO USER622 VALUES(4,36,600);
INSERT INTO USER622 VALUES(5,32,70);
INSERT INTO USER622 VALUES(6,63,960);
INSERT INTO USER622 VALUES(7,93,-960);
INSERT INTO USER622 VALUES(8,91,960.69);
COMMIT;
SELECT * FROM USER622 ORDER BY AGE;

SELECT AGE,TRUNC(AGE,-1)
FROM USER622;

--运算是聚合运算
--优先级是先拼接后算+号，所以需要括号
SELECT (TRUNC(AGE,-1) || '-' || (TRUNC(AGE,-1)+9)), TRUNC(AVG(USER622.DEPOSIT), 2)
FROM USER622
GROUP BY TRUNC(AGE,-1) -- 这样分组依然是按照年龄段分组
--GROUP BY (TRUNC(AGE,-1) || '-' || (TRUNC(AGE,-1)+9))
ORDER BY (TRUNC(AGE,-1) || '-' || (TRUNC(AGE,-1)+9));


SELECT ROUND(-1.6) FROM DUAL
--把查询复制为表
CREATE TABLE EMP_1 AS 
SELECT * FROM EMP

--11点53分

--练习1：查询EMP表中，各个年份入职的人数     
SELECT TO_CHAR(HIREDATE,'YYYY'), COUNT(1)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY')
ORDER BY TO_NUMBER(TO_CHAR(HIREDATE,'YYYY'))

--练习2：统计EMP表中，每年各个季度的招工成本（合计工资）
--1.年+季度+成本,返回三个字段
SELECT TO_CHAR(HIREDATE,'YYYY'), TO_CHAR(HIREDATE,'Q'), SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), TO_CHAR(HIREDATE,'Q')
ORDER BY TO_NUMBER(TO_CHAR(HIREDATE,'YYYY')), TO_NUMBER(TO_CHAR(HIREDATE,'Q'))

--2.返回两个字段 ，示例：1980年第4季度 + 成本 
SELECT TO_CHAR(HIREDATE,'YYYY') ||'年第'|| TO_CHAR(HIREDATE,'Q') || '季度', SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), TO_CHAR(HIREDATE,'Q')
ORDER BY TO_NUMBER(TO_CHAR(HIREDATE,'YYYY')), TO_NUMBER(TO_CHAR(HIREDATE,'Q'))

SELECT TO_CHAR(HIREDATE,'YYYY"年第"Q"季度"'), SUM(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), TO_CHAR(HIREDATE,'Q')
ORDER BY TO_NUMBER(TO_CHAR(HIREDATE,'YYYY')), TO_NUMBER(TO_CHAR(HIREDATE,'Q'))

--练习3：查询EMP表中，周六和周日入职的员工信息。
SELECT e1.*, TO_CHAR(HIREDATE,'D'), TO_CHAR(HIREDATE,'DAY')
FROM EMP e1
--WHERE TO_CHAR(HIREDATE,'D') = '7' OR TO_CHAR(HIREDATE,'D') = '1'
WHERE TO_CHAR(HIREDATE,'D') IN (1, 7)
GROUP BY TO_CHAR(HIREDATE,'YYYY'), TO_CHAR(HIREDATE,'Q')
ORDER BY TO_NUMBER(TO_CHAR(HIREDATE,'YYYY')), TO_NUMBER(TO_CHAR(HIREDATE,'Q'))

--14点30分
----建表语句------------------------------------------------
CREATE TABLE DATE_LIST(D_ID NUMBER,D_DATE DATE);

INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211020,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211005,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211018,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211029,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211120,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211105,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211118,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(1,TO_DATE(20211129,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20201020,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20200205,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20200616,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20201121,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20231020,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20230205,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20230616,'YYYYMMDD'));
INSERT INTO DATE_LIST VALUES(2,TO_DATE(20231121,'YYYYMMDD'));
COMMIT;

SELECT * FROM DATE_LIST;

--练习1：使用各种函数组合用两种方式求出DATE_LIST表中
--D_ID为1的所有日期的下个月1号
--1
SELECT dl.*, TRUNC(ADD_MONTHS(D_DATE,1),'MM')
FROM DATE_LIST dl
WHERE D_ID = 1
--2
SELECT dl.*, LAST_DAY(D_DATE) + 1
FROM DATE_LIST dl
WHERE D_ID = 1

--也可以用ROUND

--练习2：使用各种函数组合用两种方式求出DATE_LIST表中
--D_ID为2的所有日期的下一年1月1号
SELECT dl.*, TRUNC(ADD_MONTHS(D_DATE,12),'YYYY')
FROM DATE_LIST dl
WHERE D_ID = 2

--SELECT dl.*, TO_DATE(TO_CHAR(D_DATE + 365,'YYYY'),'YYYY"0101"')
--SELECT dl.*, TO_DATE(TO_CHAR(D_DATE + 365,'YYYY"0101"'),'YYYYMMDD')
--365也不稳，还是ADD_MONTH稳
SELECT dl.*, TO_DATE(TO_CHAR(TO_DATE('20240101','YYMMDD') + 365,'YYYY"0101"'),'YYYYMMDD')
FROM DATE_LIST dl
WHERE D_ID = 2

--SELECT dl.*, ROUND(D_DATE + 180,'YYYY'), ROUND(TO_DATE('20241231','YYMMDD') + 181,'YYYY')
--不能用date，+180+181+182，遇到0101，1231，碰上闰年非闰年会炸
SELECT dl.*, ROUND(ADD_MONTHS(D_DATE,6),'YYYY')
FROM DATE_LIST dl
WHERE D_ID = 2
